version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_store.sql:/docker-entrypoint-initdb.d/db_store.sql
  mystore:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      DB: ${DB}
      SECRET_KEY: ${SECRET_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "3000:3000"

volumes:
  mysql_data: